project:
  type: website

website:
  title: "Boudry Felix"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: lessons.qmd
        text: Lessons
      - href: softwares.qmd
        text: Softwares
      - href: about.qmd
        text: About

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    toc: true



